class CfgPatches
{
	class gordon_reskins_SnS_OG107
	{
		// List of units defined in this "PBO"
		units[]={};
		weapons[]=
		{
			"FP_GOR_Uniform_og107_mk3_stripeywoodland_blench",
			"FP_GOR_Uniform_og107_mk3_stripeywoodland_trop_blench",
			"FP_GOR_Uniform_og107_mk3_stripeywoodland_tuck_blench",
			"FP_GOR_Uniform_og107_mk3_stripeywoodland_tuck_trop_blench",
			"FP_GOR_Uniform_og107_mk3_stripeyarid_blench",
			"FP_GOR_Uniform_og107_mk3_stripeyarid_trop_blench",
			"FP_GOR_Uniform_og107_mk3_stripeyarid_tuck_blench",
			"FP_GOR_Uniform_og107_mk3_stripeyarid_tuck_trop_blench",
			"FP_GOR_Uniform_og107_mk3_stripeydesert_blench",
			"FP_GOR_Uniform_og107_mk3_stripeydesert_trop_blench",
			"FP_GOR_Uniform_og107_mk3_stripeydesert_tuck_blench",
			"FP_GOR_Uniform_og107_mk3_stripeydesert_tuck_trop_blench",
			"FP_GOR_Uniform_og107_mk3_ogdpm_blench",
			"FP_GOR_Uniform_og107_mk3_ogdpm_trop_blench",
			"FP_GOR_Uniform_og107_mk3_ogdpm_tuck_blench",
			"FP_GOR_Uniform_og107_mk3_ogdpm_tuck_trop_blench",
			"FP_GOR_Uniform_og107_mk3_dpm_blench",
			"FP_GOR_Uniform_og107_mk3_dpm_trop_blench",
			"FP_GOR_Uniform_og107_mk3_dpm_tuck_blench",
			"FP_GOR_Uniform_og107_mk3_dpm_tuck_trop_blench",
			"FP_GOR_Uniform_og107_mk3_ddpm_blench",
			"FP_GOR_Uniform_og107_mk3_ddpm_trop_blench",
			"FP_GOR_Uniform_og107_mk3_ddpm_tuck_blench",
			"FP_GOR_Uniform_og107_mk3_ddpm_tuck_trop_blench",
			"FP_GOR_Uniform_og107_mk3_irishdpm_blench",
			"FP_GOR_Uniform_og107_mk3_irishdpm_trop_blench",
			"FP_GOR_Uniform_og107_mk3_irishdpm_tuck_blench",
			"FP_GOR_Uniform_og107_mk3_irishdpm_tuck_trop_blench",
			"FP_GOR_Uniform_og107_mk3_irishddpm_blench",
			"FP_GOR_Uniform_og107_mk3_irishddpm_trop_blench",
			"FP_GOR_Uniform_og107_mk3_irishddpm_tuck_blench",
			"FP_GOR_Uniform_og107_mk3_irishddpm_tuck_trop_blench",
			"FP_GOR_Uniform_og107_mk3_idf_blench",
			"FP_GOR_Uniform_og107_mk3_idf_trop_blench",
			"FP_GOR_Uniform_og107_mk3_idf_tuck_blench",
			"FP_GOR_Uniform_og107_mk3_idf_tuck_trop_blench",
			"FP_GOR_Uniform_og107_mk3_greeklizard_blench",
			"FP_GOR_Uniform_og107_mk3_greeklizard_trop_blench",
			"FP_GOR_Uniform_og107_mk3_greeklizard_tuck_blench",
			"FP_GOR_Uniform_og107_mk3_greeklizard_tuck_trop_blench",
			"FP_GOR_Uniform_og107_mk3_portugueselizard_blench",
			"FP_GOR_Uniform_og107_mk3_portugueselizard_trop_blench",
			"FP_GOR_Uniform_og107_mk3_portugueselizard_tuck_blench",
			"FP_GOR_Uniform_og107_mk3_portugueselizard_tuck_trop_blench",
			"FP_GOR_Uniform_og107_mk3_danishm84_blench",
			"FP_GOR_Uniform_og107_mk3_danishm84_trop_blench",
			"FP_GOR_Uniform_og107_mk3_danishm84_tuck_blench",
			"FP_GOR_Uniform_og107_mk3_danishm84_tuck_trop_blench",
			"FP_GOR_Uniform_og107_mk3_danishm84desert_blench",
			"FP_GOR_Uniform_og107_mk3_danishm84desert_trop_blench",
			"FP_GOR_Uniform_og107_mk3_danishm84desert_tuck_blench",
			"FP_GOR_Uniform_og107_mk3_danishm84desert_tuck_trop_blench",
			"FP_GOR_Uniform_og107_mk3_alpenflage_blench",
			"FP_GOR_Uniform_og107_mk3_alpenflage_trop_blench",
			"FP_GOR_Uniform_og107_mk3_alpenflage_tuck_blench",
			"FP_GOR_Uniform_og107_mk3_alpenflage_tuck_trop_blench"
		};
		requiredVersion=0.1;
		requiredAddons[]=
		{
			"simc_mc_67_core",
			"A3_Data_F_AOW_Loadorder"
		};
	};
};

#include "CfgVehicles.cpp"
#include "CfgWeapons.cpp"